### ISSUE TITLE
Housing costs are described as per week but are annual

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#104]
See

https://github.com/PSLmodels/openfisca-uk/blob/9e575633f4244beb6ed47e035d1e0b7a25fd4819/openfisca_uk/variables/household/expense.py#L40

But I have `housing_costs.median` (household-level, weighted) at 3120 and mean at 4194, which is pretty close to the annual average of [3713 from ONS](https://www.nimblefins.co.uk/average-uk-household-budget#nogo).

**Comment by nikhilwoodruff** [comment]
Oh right, this is just the description being wrong (should be "Total housing costs"). The definition period is [weekly]( https://github.com/PSLmodels/openfisca-uk/blob/75185d05878570841e0c55332ab09d5ce4e495ce/openfisca_uk/variables/finance/expense.py#L67).

**Comment by MaxGhenis** [comment]
Fixed at some point:

https://github.com/PSLmodels/openfisca-uk/blob/c70220daf698caf43657592555c430d58df31cc5/openfisca_uk/variables/finance/expense.py#L60-L63
