### ISSUE TITLE
Confirm features of investment income

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#11]
Currently, all investment income is being taxed as capital gains. Is that improperly taxing interest and dividends?

**Comment by nikhilwoodruff** [comment]
It's not completely clear, and the [documentation ](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/789455/family-resources-survey-2017-18-background-note-methodology.pdf#page=10) for the Family Resources Survey says to treat the investment income field with high caution. There's also some nuance missing at the moment in both [interest tax](https://www.gov.uk/apply-tax-free-interest-on-savings#personal-savings-allowance) and [dividends tax](https://www.gov.uk/tax-on-dividends) in that they both work structurally similarly to Capital Gains Tax (using income tax bands but not rates) but with slightly different rates - I'm not sure at the moment how to distinguish between these types in the FRS.

**Comment by nikhilwoodruff** [comment]
Interest and dividends rules were implemented in #37 , so closing.

**Comment by MaxGhenis** [comment]
Does this pertain to interest as well as dividends? https://github.com/nikhilwoodruff/openfisca-uk/blob/master/openfisca_uk/parameters/taxes/income_tax/rates/dividend_rates.yaml

How about capital gains?

**Comment by nikhilwoodruff** [comment]
Dividends are taxed slightly differently to interest: https://github.com/nikhilwoodruff/openfisca-uk/blob/cefe0b8ffbb6ac09b57e59653c74517557969ca9/openfisca_uk/variables/person/taxes/income_tax.py#L212, and savings interest is taxed along with other interest. They also have different allowances and deductions. As for capital gains - should've mentioned, but after implementing the specific rules for interest and dividends I don't think we're actually handling it at all, as we don't have any other data for it (no other models account for it either I think)

**Comment by MaxGhenis** [comment]
I see, from that code it looks like interest is taxed closer to ordinary income than to dividends, is that right?

Filed #40 for capital gains implementation, which would be low priority since there's no data (and it's not a major source of revenue, and it's [especially elastic](https://taxfoundation.org/jct-report-shows-capital-gains-are-sensitive-to-taxation/#:~:text=Estimates%20of%20this%20elasticity%20show,than%201%20in%20absolute%20value.) to tax changes).

**Comment by MaxGhenis** [comment]
@nikhilwoodruff if we're good on investment income other than capital gains, feel free to close this.
