### ISSUE TITLE
Trouble following example to get data installed

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/openfisca-uk#159]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I followed the instructions in `README.md` to install OpenFisca-UK and download `synth_frs_2018.h5`.

I saved this file to my Downloads folder and then navigated there.  I then ran the command `openfisca-uk-data synth_frs save synth_frs_2018`

### Here is what I expected to happen:

I expected a new data file to be saved.

### Here is what actually happened:

I received an error:

```
(base) jason.debacker@JDEBACKER Downloads % openfisca-uk-data synth_frs save synth_frs_2018
Traceback (most recent call last):
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 38, in main
    return getattr(datasets[args.dataset], args.action)(*args.args)
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/datasets/frs/synth_frs.py", line 85, in save
    shutil.copyfile(data_file, SynthFRS.file(year))
  File "/Users/jason.debacker/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'synth_frs_2018'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jason.debacker/anaconda3/bin/openfisca-uk-data", line 8, in <module>
    sys.exit(main())
  File "/Users/jason.debacker/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 40, in main
    print(f"Encountered an error: {e.with_traceback()}")
TypeError: with_traceback() takes exactly one argument (0 given)
```

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.

cc @jpycroft

**Comment by nikhilwoodruff** [comment]
Hi Jason, sorry about that. To try and get this working as soon as possible on your end, I'd suggest using the setup features introduced in #154 - but if you're just using the synthetic FRS, this should now just work straight from the `pip` install. Could you try uninstalling/reinstalling `openfisca-uk` from this repo, and then just test it with:
```python
from openfisca_uk import Microsimulation
sim.calc("in_poverty_bhc")
```

I've just successfully tried that in a blank, hosted Colab notebook [here](https://colab.research.google.com/drive/12D-zrpFoPuztNcw-Ssbtbq5r7O4RcME_#scrollTo=m1SQBs8fIxNa).

**Comment by jdebacker** [comment]
Works now.  Thanks!
