### ISSUE TITLE
Change date of mid-year tax credit changes from Jun 1 to Apr 6

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#175]
[gov.uk says April 6:](https://www.gov.uk/government/publications/rates-and-allowances-tax-credits-child-benefit-and-guardians-allowance/tax-credits-child-benefit-and-guardians-allowance)
>These tables show rates and allowances for tax credits, Child Benefit and Guardian’s Allowance by tax year (6 April to 5 April).

But [EUROMOD Country Report - UK says June:](https://www.iser.essex.ac.uk/files/projects/UKMOD/EUROMOD_country_report.pdf#page=27)
![image](https://user-images.githubusercontent.com/6076111/131231628-f0148085-9ad9-4c72-9f2e-254f83f9a174.png)

Most parameters are currently set to June.

**Comment by MaxGhenis** [comment]
Looks to be April 6, e.g.: https://www.legislation.gov.uk/uksi/2021/156/regulation/1/made

**Comment by nikhilwoodruff** [comment]
Yep, so we should change the dates for the HMRC-managed benefits and double-check the DWP benefits
