### ISSUE TITLE
Account for benefit take-up rates

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/openfisca-uk#19]
Not all those eligible for benefits claim them, and not all who claim them report them. The former should be dealt with by using the compiled benefit take-up rates by the DWP based on the FRS and administrative data, while keeping the people who already claim them consistent. The latter requires a bit more consideration.

**Comment by MaxGhenis** [comment]
This is done right?

**Comment by nikhilwoodruff** [comment]
Yep, closing.
