### ISSUE TITLE
116% marginal tax rate for parents starting around £16,000 employment income

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#200]
PolicyEngine is showing a 116% marginal tax rate starting at about £16,000, with varying employment-income-width. All these examples have only employment income.

One adult, one child:

![image](https://user-images.githubusercontent.com/6076111/132116788-328db26b-43d4-4e36-a74c-628d75d34d40.png)

Two parents, one child:
![image](https://user-images.githubusercontent.com/6076111/132116857-c66143d0-f8d1-45ae-9072-350bd8cc5e79.png)

Two parents, two children:
![image](https://user-images.githubusercontent.com/6076111/132116942-e835d738-2c5e-43f7-b074-b30123dbb68c.png)

Looks OK for a couple with no children:
![image](https://user-images.githubusercontent.com/6076111/132116929-8a834db8-201e-4a5c-87af-c5fd83550cbe.png)

**Comment by nikhilwoodruff** [comment]
It was the policy parameters overriding the model automatic UC assigning (the user explicitly claiming both tax credits and UC). To be clear, not an issue with openfisca-uk here.

**Comment by MaxGhenis** [comment]
Fixed in https://github.com/UBICenter/policyengine-uk/pull/166
