### ISSUE TITLE
Rename age variables

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#32]
Per our follow up discussion from #30, I'd suggest:
* `basic_income_u18` -> `age_u18`
* `basic_income_adult` -> `age_1864`
* `basic_income_pensioner` -> `age_65plus`

And then the parameter names can be something like `ubi_age_{u18,1864,65plus}`, or just `ubi_*`.

**Comment by nikhilwoodruff** [comment]
I think we can close this given it's now very different to the repo now.
