### ISSUE TITLE
Create new disabled flag for UBI

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#47]
Should include current disabled flag, plus:
* income-based ESA
* registered disabled
* Equality Act flags
* PIP
* IIDB
https://github.com/PSLmodels/openfisca-uk/blob/86c76547670ba2d4b6c9b1b66f7139a44a098f02/openfisca_uk/variables/person/disability.py#L13-L20

NB: incapacity benefit and SDA have been rolled into ESA. Constant Attendance Allowance and New Style ESA are absent from FRS. Disability premiums are added into their respective benefits, so can't be disentangled to add to the logic.

**Comment by nikhilwoodruff** [comment]
Also add PIP and ESA-income to disabled flag at the moment
