### ISSUE TITLE
Remove unnecessary files from repo

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/openfisca-uk#50]
I'm noticing a few files that I think are unnecessary and could be removed from the repo:

1. `debug.log`: this file listed in the `.gitignore`, but is checked into the master.
2.  `.vscode` directory and files within

**Comment by nikhilwoodruff** [comment]
Thanks Jason- yep, I'll remove the debug.log, that's not doing anything. However, the .vscode has a few useful code snippets related to defining new OpenFisca constructs, such as [variables, formulas](https://github.com/PSLmodels/openfisca-uk/blob/master/.vscode/snippets/python.json) and [tests ](https://github.com/PSLmodels/openfisca-uk/blob/master/.vscode/snippets/yaml.json)that I've found to be pretty time-saving: just wondering if there's a standard place to put these outside of the repo?

**Comment by MaxGhenis** [comment]
Keeping `.vscode/` here seems OK to me, at least for now, maybe just add a `README.md` to explain how to use it?
