### ISSUE TITLE
ESA_income_reported_personal is weekly rather than annual

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/openfisca-uk#86]
Should be fixed in #83 but just to note it
![image](https://user-images.githubusercontent.com/6076111/106185817-363e4900-6158-11eb-96e5-f2ff5a96491e.png)

**Comment by nikhilwoodruff** [comment]
Yep, this variable no longer exists - ESA_income_reported is now person-level to avoid ambiguity, so closing.
